# Generated by Django 4.0.2 on 2022-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('dateTimeCollection', models.DateTimeField(auto_now_add=True)),
                ('dateTimeReceived', models.DateTimeField(auto_now=True)),
                ('dateTimeReported', models.DateTimeField()),
            ],
        ),
    ]
